<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CarouselSlide;
use Illuminate\Support\Str;

class CarouselSlideSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $slides = [
            [
                'title' => 'Welcome to ICCR Tanzania',
                'subtitle' => 'Uniting Catholic Students Across Tanzania',
                'description' => 'Join us in building a generation of faithful leaders through the Holy Spirit in prayer, worship, and fellowship.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/welcome.jpg',
                'animation_type' => 'slide-fade',
                'button_1_text' => 'Learn More',
                'button_1_url' => '/about',
                'button_2_text' => 'Join Us',
                'button_2_url' => '/get-involved',
                'gradient_from' => 'green-600',
                'gradient_via' => 'blue-600',
                'gradient_to' => 'green-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 1,
                'is_active' => true,
            ],
            [
                'title' => '🔥 URGENT CONFERENCE',
                'subtitle' => 'International Easter Conference 2026',
                'description' => 'USIFANYE MISTAKE KABISA KUKOSA KONGAMANO HILI! Toka nimeuzulia, nakuwa mpya kifikra, kiujuzi, kiuchumi, mtazamo na kimahusiano, kifamilia na natiwa ujasiri wa uthubutu limetumika kuwa daraja kwa ajili ya watu wengi. MAMBO NI MAZURI - TWENDE KWA PAMOJA!',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/easter-conference.jpg',
                'animation_type' => 'slide-zoom',
                'button_1_text' => 'Register Now',
                'button_1_url' => '/events',
                'button_2_text' => 'Learn More',
                'button_2_url' => '/events',
                'gradient_from' => 'red-600',
                'gradient_via' => 'red-800',
                'gradient_to' => 'red-800',
                'is_urgent' => true,
                'urgent_badge_text' => '🔥 URGENT',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'title' => 'Night of Praise',
                'subtitle' => 'Powerful Worship & Fellowship',
                'description' => 'Join us for an evening of powerful worship, prayer, and fellowship. This event brings together students from across Tanzania for a night of praise and spiritual renewal.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/night-of-praise.jpg',
                'animation_type' => 'slide-fade',
                'button_1_text' => 'Register',
                'button_1_url' => '/events',
                'button_2_text' => 'View Events',
                'button_2_url' => '/events',
                'gradient_from' => 'blue-600',
                'gradient_via' => 'purple-600',
                'gradient_to' => 'blue-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 3,
                'is_active' => true,
            ],
            [
                'title' => 'Regional Spiritual Camp',
                'subtitle' => 'Deepen Your Relationship with God',
                'description' => 'A multi-day spiritual camp focused on deepening your relationship with God through prayer, teaching, and fellowship. Open to all students from regional colleges.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/spiritual-camp.jpg',
                'animation_type' => 'slide-zoom',
                'button_1_text' => 'Join Camp',
                'button_1_url' => '/events',
                'button_2_text' => null,
                'button_2_url' => null,
                'gradient_from' => 'purple-600',
                'gradient_via' => 'pink-600',
                'gradient_to' => 'purple-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 4,
                'is_active' => true,
            ],
            [
                'title' => 'Open Gate Camp',
                'subtitle' => 'Moshi & Arusha Regions',
                'description' => 'A transformative multi-day camp bringing together students from Moshi and Arusha regions. Experience powerful worship, inspiring teachings, and life-changing encounters with the Holy Spirit.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/open-gate-camp.jpg',
                'animation_type' => 'slide-fade',
                'button_1_text' => 'Register Now',
                'button_1_url' => '/events',
                'button_2_text' => 'Learn More',
                'button_2_url' => '/events',
                'gradient_from' => 'orange-600',
                'gradient_via' => 'red-600',
                'gradient_to' => 'orange-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 5,
                'is_active' => true,
            ],
            [
                'title' => 'Perfect Vision Conference',
                'subtitle' => 'Gain Clarity in Your Spiritual Journey',
                'description' => 'A powerful conference focused on gaining clarity in your spiritual journey and life purpose. Through dynamic worship, prophetic ministry, and practical teaching, discover God\'s perfect vision for your life.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/perfect-vision.jpg',
                'animation_type' => 'slide-zoom',
                'button_1_text' => 'Join Conference',
                'button_1_url' => '/events',
                'button_2_text' => null,
                'button_2_url' => null,
                'gradient_from' => 'indigo-600',
                'gradient_via' => 'purple-600',
                'gradient_to' => 'indigo-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 6,
                'is_active' => true,
            ],
            [
                'title' => 'Usiku wa Sifa',
                'subtitle' => 'Night of Praise - Dar es Salaam',
                'description' => 'Experience an unforgettable night of praise and worship in Dar es Salaam. Join hundreds of students as we lift our voices in unity, declaring God\'s goodness and faithfulness.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/usiku-wa-sifa.jpg',
                'animation_type' => 'slide-fade',
                'button_1_text' => 'Register',
                'button_1_url' => '/events',
                'button_2_text' => 'View Details',
                'button_2_url' => '/events',
                'gradient_from' => 'yellow-600',
                'gradient_via' => 'orange-600',
                'gradient_to' => 'yellow-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 7,
                'is_active' => true,
            ],
            [
                'title' => 'NexGen Leadership School',
                'subtitle' => 'Empowering the Next Generation',
                'description' => 'A comprehensive leadership development program designed for the next generation of leaders. This intensive camp combines spiritual formation, practical leadership training, and strategic planning.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/nexgen-leadership.jpg',
                'animation_type' => 'slide-zoom',
                'button_1_text' => 'Apply Now',
                'button_1_url' => '/events',
                'button_2_text' => 'Learn More',
                'button_2_url' => '/events',
                'gradient_from' => 'teal-600',
                'gradient_via' => 'cyan-600',
                'gradient_to' => 'teal-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 8,
                'is_active' => true,
            ],
            [
                'title' => 'Campus Chapters',
                'subtitle' => 'Join Your Local Chapter',
                'description' => 'Connect with fellow Catholic students on your campus. Our chapters provide a supportive community for spiritual growth, fellowship, and service.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/campus-chapters.jpg',
                'animation_type' => 'slide-fade',
                'button_1_text' => 'Find Chapter',
                'button_1_url' => '/get-involved',
                'button_2_text' => 'Contact Us',
                'button_2_url' => '/contact',
                'gradient_from' => 'green-600',
                'gradient_via' => 'blue-600',
                'gradient_to' => 'green-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 9,
                'is_active' => true,
            ],
            [
                'title' => 'Graduate Network',
                'subtitle' => 'Stay Connected After Graduation',
                'description' => 'Your journey doesn\'t end at graduation. Join the ICCR Tanzania Graduate Network and continue growing in faith while making a difference in your community.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/graduate-network.jpg',
                'animation_type' => 'slide-zoom',
                'button_1_text' => 'Join Network',
                'button_1_url' => '/graduate',
                'button_2_text' => 'Learn More',
                'button_2_url' => '/graduate',
                'gradient_from' => 'blue-600',
                'gradient_via' => 'indigo-600',
                'gradient_to' => 'blue-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 10,
                'is_active' => true,
            ],
            [
                'title' => 'Resources & Media',
                'subtitle' => 'Spiritual Growth Materials',
                'description' => 'Access our library of resources including videos, articles, study guides, and more to support your spiritual journey and ministry.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/resources.jpg',
                'animation_type' => 'slide-fade',
                'button_1_text' => 'Browse Resources',
                'button_1_url' => '/resources',
                'button_2_text' => 'View Media',
                'button_2_url' => '/media',
                'gradient_from' => 'purple-600',
                'gradient_via' => 'pink-600',
                'gradient_to' => 'purple-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 11,
                'is_active' => true,
            ],
            [
                'title' => 'Prayer & Worship',
                'subtitle' => 'Join Our Weekly Gatherings',
                'description' => 'Experience the power of corporate prayer and worship. Join us for weekly prayer meetings, worship nights, and special prayer services.',
                'image_url' => 'https://res.cloudinary.com/dpyppzvzj/image/upload/v1706000000/iccr/prayer-worship.jpg',
                'animation_type' => 'slide-zoom',
                'button_1_text' => 'Join Prayer',
                'button_1_url' => '/get-involved',
                'button_2_text' => null,
                'button_2_url' => null,
                'gradient_from' => 'green-600',
                'gradient_via' => 'emerald-600',
                'gradient_to' => 'green-800',
                'is_urgent' => false,
                'urgent_badge_text' => null,
                'order' => 12,
                'is_active' => true,
            ],
        ];

        foreach ($slides as $slide) {
            CarouselSlide::create($slide);
        }
    }
}

